### ISSUE TITLE
Relative links are not working when documentation is hosted on ReadtheDocs

### ISSUE THREAD

**Issue by nfelt14** [realtimeprojects/mkdocs-ezglossary#16]
It appears that the `href` element is being populated with a relative link which is causing the links to route to a 404 page when the documentation is hosted on readthedocs.

- The home page is located at `<rtd_url>/latest/`
- The glossary is located at `<rtd_url>/latest/glossary`
- The relative links from the readme (home page) are routing to `<rtd_url>/glossary#id`, but that page doesn't exist
- The relative links from other pages (not the home page) are working properly

**Comment by nfelt14** [comment]
@realtimeprojects, any idea if this would be able to be resolved any time soon?

**Comment by realtimeprojects** [comment]
thank you for your PR and for fixing this issue. Looks good to me. I just made a [new release](https://realtimeprojects.github.io/mkdocs-ezglossary/releases/#v1610) with your changes.
