### ISSUE TITLE
`inline_refs` doesn't work with `list` or `full`

### ISSUE THREAD

**Issue by pekkaklarck** [realtimeprojects/mkdocs-ezglossary#19]
Based on the [docs](https://realtimeprojects.github.io/mkdocs-ezglossary/usage/definition/#configuration) I should be able to use `inline_refs: list`, but I got this error:

> Config value 'plugins': Plugin 'ezglossary' option 'inline_refs': Expected one of: ('none', 'short', 'full') but received: 'list'

I then tried the proposed `full` option, but that resulted with a different error:

> jinja2.exceptions.TemplateNotFound: refs-full.html

**Comment by realtimeprojects** [comment]
Will be fixed with v1.7.0 release. The correct configuration entry is: `inline_refs: list`.
