### ISSUE TITLE
`tooltip: heading` doesn't work

### ISSUE THREAD

**Issue by pekkaklarck** [realtimeprojects/mkdocs-ezglossary#20]
Based on the [docs](https://realtimeprojects.github.io/mkdocs-ezglossary/usage/linking/#tooltips) `tooltip: heading` should work, but I got this error when trying to use it:

> UnboundLocalError: cannot access local variable '_tooltip' where it is not associated with a value

Using `tooltip: full` and `tooltip: none` work as documented.

**Comment by realtimeprojects** [comment]
Thanks for your feedback. In fact, this is an documentation error. The correct configuration is `tooltip: short` instead of `tooltip: heading`. The documentation has been updated now accordingly.
