### ISSUE TITLE
Term lookup should be case-insensitive

### ISSUE THREAD

**Issue by pekkaklarck** [realtimeprojects/mkdocs-ezglossary#21]
It seems to be that the term lookup is case-sensitive. For example, if I have a definition like
```
term:Keyword
:  Keywords are very important for us.
```
it is possible to refer to it using  `<term:Keyword>` but `<term:keyword>` doesn't work. This results with incorrect capitalization when the term is used in a middle of a sentence. Workarounds include defining the term in both formats and using syntax `<term:Keyword|keyword>`, but both require annoying extra boilerplate and are easy to forget.

In my opinion the term lookup should be case-insensitive. I believe it should be the default, but would be fine having an option to enable it. I tried to search for such option but couldn't find anything.

**Comment by pekkaklarck** [comment]
This is a similar problem as plural usages like `<term:GPUs>` not matching singular definitions like `term:GPU` discussed in #18. Case-insensitivity ought to be easier to implement, though.

**Comment by realtimeprojects** [comment]
Starting from version `v1.7.0`, ezglossary you can [disable case-sensitivity](https://realtimeprojects.github.io/mkdocs-ezglossary/usage/linking/#case-sensitivity) by setting the configuration `ignore_case: true`.

**Comment by pekkaklarck** [comment]
That's great news! Apparently 1.7 was just released. I'll give it a try shorly.
