### ISSUE TITLE
Plural configuration doesn't work

### ISSUE THREAD

**Issue by pekkaklarck** [realtimeprojects/mkdocs-ezglossary#22]
v1.7.0 ought to support plural lookups of singular terms (#18) but when I tried it both `plurals: inflect` and `plurals: en` yield this error:
> AttributeError: 'GlossaryConfig' object has no attribute 'plurals'

**Comment by realtimeprojects** [comment]
Another configuration bug. Unfortunatly the configuration check is not covered by the tests causing this issues. This is now fixed with `v1.7.1`.
Thanks for your feedback!

**Comment by pekkaklarck** [comment]
I tested v1.7.1 and plural usages work otherwise, but they are not listed in the glossary. I submitted #24 about that.
