### ISSUE TITLE
Term definition doesn't support formatting

### ISSUE THREAD

**Issue by silopolis** [realtimeprojects/mkdocs-ezglossary#3]
As an IT pro, my definitions often get formatted defined term like in:

```
**`mycommand`**
:  	My command description
```

This is currently not supported and would be a very welcome improvement of this great plugin!

Thanks for your work
Take care

**Comment by realtimeprojects** [comment]
This is a great idea, however, it is not done quickly, some minor refactoring is required to implement this.
Nevertheless I try to address this the next days.

**Comment by realtimeprojects** [comment]
Meanwhile, in case all your definitions use the same formatting, consider using a [custom definition template](https://realtimeprojects.github.io/mkdocs-ezglossary/usage/customization/#:~:text=Term%20definition-,%C2%B6,-The%20definition.html) like:

```python
<dt>
    <strong><code><a name="{{ target }}">{{ term }}</a></code><strong>
</dt>
<dd>
    {{ definition|safe }}
    <br>
    {{ reflink }}
</dd>
```

**Comment by realtimeprojects** [comment]
@silopolis Luckily, I found an easy way to implement it, however I did not spend much time in testing it. Hence, there is a `v1.5.7a1` alpha-version available where this feature should work. It would be great if you could test it a little bit for giving me some feedback.
