### ISSUE TITLE
Unable to link to glossary inside a table cell

### ISSUE THREAD

**Issue by nfelt14** [realtimeprojects/mkdocs-ezglossary#9]
I have a table where I want to create a link to a glossary item in the first cell with custom link text. I am unable to do this due to the pipe character being used to separate out the custom link text.

Ideally I should be able to do something like this, but I am unable to at this point.
```
| Row 1                        | Row 2                 |
|------------------------|-------------------|
| <item:|custom text> | second cell item |
```

**Comment by realtimeprojects** [comment]
fixed with new release v1.5.9.

However, in order to use custom text in a table, you need to quote the `| ` (see also in [documentation](https://realtimeprojects.github.io/mkdocs-ezglossary/usage/linking/#individual-reference-texts)):

```<term:section\|glossary sections>```
